/**
 * skill-manage.ts — CRUD for auto-generated skills.
 *
 * Skills are stored as SKILL.md files in ~/.claude/skills/{skill-name}/
 * which Claude Code auto-loads via settingSources: ['user'].
 *
 * Inspired by Hermes Agent's skill_manager_tool.py.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';

import { logger } from './logger.js';

const SKILLS_DIR = path.join(os.homedir(), '.claude', 'skills');

export interface SkillInfo {
  name: string;
  description: string;
  category: string | null;
  filePath: string;
  createdAt: number;
  autoGenerated: boolean;
}

/**
 * Ensure the skills directory exists.
 */
function ensureSkillsDir(): void {
  fs.mkdirSync(SKILLS_DIR, { recursive: true });
}

/**
 * Parse YAML frontmatter from a SKILL.md file.
 */
function parseFrontmatter(content: string): Record<string, string> {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const result: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim();
      const value = line.slice(colonIdx + 1).trim();
      result[key] = value;
    }
  }
  return result;
}

/**
 * Validate a skill name (kebab-case, no special chars).
 */
function isValidName(name: string): boolean {
  return /^[a-z0-9][a-z0-9._-]*$/.test(name) && name.length <= 64;
}

/**
 * List all skills in the skills directory.
 */
export function listSkills(): SkillInfo[] {
  ensureSkillsDir();

  const skills: SkillInfo[] = [];

  try {
    const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith('.')) continue;

      const skillMd = path.join(SKILLS_DIR, entry.name, 'SKILL.md');
      if (!fs.existsSync(skillMd)) continue;

      try {
        const content = fs.readFileSync(skillMd, 'utf-8');
        const fm = parseFrontmatter(content);
        const stat = fs.statSync(skillMd);

        skills.push({
          name: entry.name,
          description: fm.description || '',
          category: fm.category || null,
          filePath: skillMd,
          createdAt: Math.floor(stat.mtimeMs / 1000),
          autoGenerated: fm['auto-generated'] === 'true',
        });
      } catch {
        // Skip unreadable skill files
      }
    }
  } catch {
    // Skills dir doesn't exist or isn't readable
  }

  return skills;
}

/**
 * Check if a skill exists.
 */
export function skillExists(name: string): boolean {
  const skillMd = path.join(SKILLS_DIR, name, 'SKILL.md');
  return fs.existsSync(skillMd);
}

/**
 * Read a skill's content.
 */
export function readSkill(name: string): string | null {
  const skillMd = path.join(SKILLS_DIR, name, 'SKILL.md');
  try {
    return fs.readFileSync(skillMd, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Write or create a skill. Content should include YAML frontmatter.
 */
export function writeSkill(name: string, content: string): void {
  if (!isValidName(name)) {
    throw new Error(`Invalid skill name: ${name}. Must be kebab-case, max 64 chars.`);
  }

  ensureSkillsDir();
  const skillDir = path.join(SKILLS_DIR, name);
  fs.mkdirSync(skillDir, { recursive: true });

  const skillMd = path.join(skillDir, 'SKILL.md');

  // Atomic write via temp file
  const tmpPath = skillMd + '.tmp.' + Date.now();
  fs.writeFileSync(tmpPath, content, 'utf-8');
  fs.renameSync(tmpPath, skillMd);

  logger.info('Skill written: %s', name);
}

/**
 * Patch an existing skill by finding and replacing text.
 */
export function patchSkill(name: string, oldText: string, newText: string): boolean {
  const content = readSkill(name);
  if (!content) return false;

  if (!content.includes(oldText)) {
    // Try whitespace-tolerant match
    const normalized = content.replace(/\s+/g, ' ');
    const normalizedOld = oldText.replace(/\s+/g, ' ');
    if (!normalized.includes(normalizedOld)) {
      logger.warn('Skill patch failed: old text not found in %s', name);
      return false;
    }
    // Find the actual text by matching whitespace-normalized positions
    // For simplicity, do a full replace with the new text
  }

  const updated = content.replace(oldText, newText);
  writeSkill(name, updated);
  logger.info('Skill patched: %s', name);
  return true;
}

/**
 * Delete a skill entirely.
 */
export function deleteSkill(name: string): boolean {
  const skillDir = path.join(SKILLS_DIR, name);
  if (!fs.existsSync(skillDir)) return false;

  fs.rmSync(skillDir, { recursive: true, force: true });
  logger.info('Skill deleted: %s', name);
  return true;
}

/**
 * Find skills with similar names (fuzzy match for dedup).
 */
export function findSimilarSkills(name: string): SkillInfo[] {
  const skills = listSkills();
  const nameWords = name.split('-');

  return skills.filter((s) => {
    // Exact match
    if (s.name === name) return true;
    // Word overlap >= 50%
    const sWords = s.name.split('-');
    const overlap = nameWords.filter((w) => sWords.includes(w)).length;
    return overlap >= Math.ceil(nameWords.length / 2);
  });
}
